name: mobileprojek
description: "Proyek Flutter aplikasi Info Negara."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Saya perbaiki rentang SDK Anda

# --- DEPENDENSI UTAMA APLIKASI ---
dependencies:
  # Ketergantungan Inti Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Jaringan & API
  http: ^1.1.0 

  # Penyimpanan Lokal (Database)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Layanan Lokasi & Peta
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  permission_handler: ^11.0.1
  flutter_map: ^6.1.0 # Versi terbaru
  latlong2: ^0.9.0 # Versi terbaru

  # Notifikasi & Waktu
  flutter_local_notifications: ^17.2.1
  timezone: ^0.9.0

  # Utilitas
  crypto: ^3.0.3
  image_picker: ^1.0.4
  path_provider: ^2.1.1

  # --- TAMBAHAN UNTUK FITUR BARU ---
  intl: ^0.19.0 # Untuk format angka
  dropdown_search: ^5.0.6 # Untuk dropdown pencarian
  url_launcher: ^6.3.1

  fl_chart: ^0.66.0  # Untuk grafik batang
  # --------------------------------

# --- DEPENDENSI PENGEMBANGAN (DEV) ---
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0 # Versi terbaru

  # Generator Kode (Penting untuk Hive)
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

# --- KONFIGURASI SPESIFIK FLUTTER ---
flutter:
  uses-material-design: true
  assets:
    - assets/Logoprojek.png