name: mobileprojek
description: "Proyek Flutter aplikasi Info Negara." # Deskripsi bisa Anda ubah
publish_to: 'none' # Mencegah publikasi tidak sengaja ke pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.0

# --- DEPENDENSI UTAMA APLIKASI ---
# --- DEPENDENSI UTAMA APLIKASI ---
dependencies:
  # Ketergantungan Inti Flutter
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Jaringan & API
  http: ^1.1.0 # Untuk memanggil API (RestCountries, Currency, Nominatim)

  # Penyimpanan Lokal (Database)
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # Layanan Lokasi & Peta
  geolocator: ^10.1.0 # Mendapatkan lokasi GPS
  geocoding: ^2.1.1 # Konversi koordinat ke alamat
  permission_handler: ^11.0.1 # Meminta izin (lokasi, notifikasi)
  flutter_map: ^8.2.2 # Menampilkan peta
  latlong2: ^0.9.1 # Helper untuk koordinat peta
  # google_maps_flutter: ^2.7.0  <-- PASTIKAN INI SUDAH DIHAPUS

  # Notifikasi & Waktu
  flutter_local_notifications: ^17.2.1 # Menampilkan notifikasi lokal
  timezone: ^0.9.0 # Untuk data zona waktu

  # Utilitas
  crypto: ^3.0.3 # Untuk hashing password (SHA-256)
  image_picker: ^1.0.4 # Mengambil gambar dari galeri (foto profil)
  path_provider: ^2.1.1 # Mendapatkan path direktori aplikasi
# --- DEPENDENSI PENGEMBANGAN (DEV) ---
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Aturan analisis kode (opsional)

  # Generator Kode (Penting untuk Hive)
  # Jalankan "flutter pub run build_runner build" setelah mengubah Model Hive
  build_runner: ^2.4.6
  hive_generator: ^2.0.0

# --- KONFIGURASI SPESIFIK FLUTTER ---
flutter:
  uses-material-design: true

  # Aset (Gambar, dll.)
  # Pastikan file ini ada di folder 'assets' di root proyek Anda
  assets:
    - assets/Logoprojek.png
    - assets/Afrika.png
    - assets/AmerikaSelatan.png
    - assets/AmerikaUtara.png
    - assets/Asia.png
    - assets/Australia&Oceania.png
    - assets/Europe.png

  # Font Kustom (Contoh)
  # Untuk menambahkan font, hapus tanda '#' di bawah dan sesuaikan
  # fonts:
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700